<?
$aMenuLinks = Array(
	Array(
		"одежда", 
		"/shop/catalog/odezhda/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"джерси", 
		"/shop/catalog/8/filter/team-is-go-or-go%20hockey/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Аксессуары", 
		"/shop/catalog/8/filter/product-is-accessories/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Сувениры", 
		"/shop/catalog/8/filter/product-is-souvenirs/apply/", 
		Array(), 
		Array(), 
		"" 
	),
	Array(
		"Новинки", 
		"/shop/catalog/8/filter/hit-is-new/apply/", 
		Array(), 
		Array(), 
		"" 
	)
);
?>